### ISSUE TITLE
indications to start the server

### ISSUE THREAD

**Issue by nherbaut** [SPLA/VARIAMOS-SERVICES#1]
could you please add some indication on how to launch the server?

I seems that there's no maven plugin configured, thus my IDE doesn't really know how to launch it.

How about using springboot? @danielgara @6ucky

**Comment by danielgara** [comment]
Hi @nherbaut 

Steps:

1) Clone the repository.
2) Download Eclipse EE (must be Eclipse "enterprise edition", it doesn't matter if it is the oxygen version, or the latest)
3) Open Eclipse, and Click Import new project. There you must select "Maven project". Then, look for the VariaMos-Services folder and select it.
4) Download apache tomcat (in order to run the project) -> I recommend version 8.5
5) Right click over the eclipse project -> Run -> Run on server (select the apache tomcat folder installation)
6) The project should be running, and a welcome message should appear.

**Note:** If you have VariaMos-Web project running over 8080, and the VariaMos-Services also running over 8080 port. It could generate some conflicts. So, I recommend to change the Eclipse server to run over 8090 or something like that.
